[package]
name = "arm9"
version = "0.1.0"
edition = "2021"

[dependencies]
ironds = { path = "../../ironds", features = ["arm9"] }
arrayvec = { version = "0.7.2", default-features = false }

[profile.dev]
opt-level = 3
